apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ecom-alerts
spec:
  groups:
    - name: ecom.burn-rate
      rules:
        - alert: ApiHighErrorBudgetBurn
          expr: job:http_requests:rate5m > 100
          for: 5m
          labels:
            severity: page
