apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ecom-recording-rules
spec:
  groups:
    - name: ecom.sli
      rules:
        - record: job:http_requests:rate5m
          expr: sum(rate(http_requests_total[5m])) by (job)
