---
# roles/os-hardening/molecule/default/converge.yml
- name: Converge
  hosts: all
  become: true
  roles:
    - role: os-hardening

  post_tasks:
    - name: Verify swap is off
      command: swapon --show
      register: swap_result
      failed_when: swap_result.stdout | length > 0

    - name: Verify ip_forward
      command: sysctl net.ipv4.ip_forward
      register: ipfwd
      failed_when: "'= 1' not in ipfwd.stdout"